package net.kirvvi.theforgottenexpance.entity.client.mummy;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class MummyAnimations {


    public static final AnimationDefinition MODEL_WALKING = AnimationDefinition.Builder.withLength(3.6f).looping()
            .addAnimation("rightleg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.posVec(0f, 0f, -1.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.posVec(0f, 1f, -4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.65f, KeyframeAnimations.posVec(0f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, -6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.posVec(0f, 0f, -6f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("rightleg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.65f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leftleg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.posVec(0f, 0f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.posVec(0f, 1f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.65f, KeyframeAnimations.posVec(0f, 0f, -2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0.5f, -6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.posVec(0f, -0.5f, -6f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leftleg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-2.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.degreeVec(2.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1f, KeyframeAnimations.degreeVec(20.05f, -0.08f, -4.31f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.degreeVec(-9.95f, -0.08f, -4.31f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-2.45f, -0.08f, -4.31f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.degreeVec(2.55f, -0.08f, -4.31f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.65f, KeyframeAnimations.degreeVec(10.05f, -0.08f, -4.31f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(-7.45f, -0.08f, -4.31f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.degreeVec(-7.45f, -0.08f, -4.31f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0.5f, 2f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.posVec(0.12f, 1.88f, 6.59f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2f, KeyframeAnimations.posVec(-1.4f, 1.8f, 6.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(-2.88f, 3.17f, 5.48f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.45f, KeyframeAnimations.posVec(-3.1f, 2.77f, 5.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(-1.8f, 2.13f, 5.63f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.posVec(-1.8f, 2.13f, 5.63f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.posVec(-1.8f, 2.13f, 5.63f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.posVec(-1.8f, 2.13f, 5.63f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7f, KeyframeAnimations.posVec(-1.8f, 1.74f, 5.63f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(-1.8f, 1.74f, 5.63f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(-1f, 1.5f, 4.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.9f, KeyframeAnimations.posVec(-1f, 1.5f, 4.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.95f, KeyframeAnimations.posVec(-1f, 1.5f, 4.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1f, KeyframeAnimations.posVec(-1f, 1.6f, 4.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.05f, KeyframeAnimations.posVec(-1f, 1.8f, 4.55f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1f, KeyframeAnimations.posVec(-1f, 1.4f, 4.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.15f, KeyframeAnimations.posVec(-1f, 1.4f, 4.5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.35f, KeyframeAnimations.posVec(0.4f, 1.5f, 4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4f, KeyframeAnimations.posVec(0.8f, 1.5f, 4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45f, KeyframeAnimations.posVec(1f, 1.5f, 4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7f, KeyframeAnimations.posVec(4f, 0.74f, 0.43f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.posVec(4f, 0.79f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.95f, KeyframeAnimations.posVec(0.6f, -0.02f, 0.16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2f, KeyframeAnimations.posVec(-0.8f, 1.45f, 1.33f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.35f, KeyframeAnimations.posVec(-3.5f, 1.94f, 1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.posVec(-4.19f, 1.89f, 1.15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.45f, KeyframeAnimations.posVec(-4.5f, 2f, 0.98f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.7f, KeyframeAnimations.posVec(-1.7f, 0.49f, -2.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.85f, KeyframeAnimations.posVec(-2f, 0.17f, -1.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.05f, KeyframeAnimations.posVec(-0.76f, 0.9f, -1.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.15f, KeyframeAnimations.posVec(0.26f, 1f, -2.26f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(1f, 1f, -3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.35f, KeyframeAnimations.posVec(2f, 0.76f, -2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.posVec(1f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(29.98f, 1.25f, -2.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.45f, KeyframeAnimations.degreeVec(27.66f, -14.25f, 8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(28.73f, -12.34f, 1.65f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.degreeVec(28.73f, -12.34f, 1.65f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(28.73f, -12.34f, 1.65f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.05f, KeyframeAnimations.degreeVec(27.04f, -11.57f, -0.75f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1f, KeyframeAnimations.degreeVec(24.24f, -11.52f, -0.79f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.15f, KeyframeAnimations.degreeVec(23.49f, -10.21f, 0.29f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4f, KeyframeAnimations.degreeVec(22.5f, -6.21f, -7.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.45f, KeyframeAnimations.degreeVec(22.41f, -7.5f, -9.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(7.16f, 16.81f, -12.88f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(11.32f, 14.39f, 2.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.2f, KeyframeAnimations.degreeVec(18.67f, -6.69f, 3.03f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.45f, KeyframeAnimations.degreeVec(18.95f, -17.64f, 13.4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.65f, KeyframeAnimations.degreeVec(4.6f, -26.21f, 6.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.85f, KeyframeAnimations.degreeVec(10.66f, -35.34f, 0.99f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.05f, KeyframeAnimations.degreeVec(13.78f, -19.11f, -2.57f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.15f, KeyframeAnimations.degreeVec(13.63f, -7.32f, -1.19f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.3f, KeyframeAnimations.degreeVec(14.57f, 10.14f, -5.26f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.degreeVec(23.78f, 2.61f, -1.92f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tors",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tors",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("righthand",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-11f, -6f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.posVec(-11f, -6f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(-11.06f, -5.44f, 7.23f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.posVec(-11f, -4f, 8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.95f, KeyframeAnimations.posVec(-11.5f, -5f, 8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1f, KeyframeAnimations.posVec(-11.4f, -4.33f, 8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.3f, KeyframeAnimations.posVec(-11.14f, -3f, 8.99f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.55f, KeyframeAnimations.posVec(-10.84f, -1.47f, 9.72f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.posVec(-11.14f, -1.33f, 9.82f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7f, KeyframeAnimations.posVec(-11f, -3f, 10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.95f, KeyframeAnimations.posVec(-11f, -1f, 10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.posVec(-12f, -6f, 4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.45f, KeyframeAnimations.posVec(-12f, -6f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.posVec(-11.88f, -5.87f, 7.51f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.7f, KeyframeAnimations.posVec(-11f, -5f, 8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(-9f, -3.78f, 8.81f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.8f, KeyframeAnimations.posVec(-7.97f, -2.38f, 9.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.85f, KeyframeAnimations.posVec(-8.5f, -1f, 10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.95f, KeyframeAnimations.posVec(-9.85f, 0.65f, 11.03f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.05f, KeyframeAnimations.posVec(-11f, 0f, 10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.15f, KeyframeAnimations.posVec(-10f, -1f, 10f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(-11f, -3f, 9f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.35f, KeyframeAnimations.posVec(-12f, -4f, 8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.55f, KeyframeAnimations.posVec(-13f, -5f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("righthand",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, -47.5f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.degreeVec(-90f, -47.5f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-90f, -57.5f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.degreeVec(-90f, -65f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1f, KeyframeAnimations.degreeVec(-82.5f, -65f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.degreeVec(-66.54f, -82.04f, 73.54f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-77.81f, -74.86f, 85.02f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(-66.54f, -82.04f, 73.54f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.degreeVec(-85.52f, -45.1f, 93.63f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-83.51f, -60.03f, 91.15f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.65f, KeyframeAnimations.degreeVec(-84.1f, -57.55f, 91.82f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.9f, KeyframeAnimations.degreeVec(13.27f, -74.9f, -6.56f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(40.33f, -85.85f, -33.6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(-79.48f, -72.41f, 86.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.degreeVec(-91.84f, -50.22f, 100.7f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-1f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.3f, KeyframeAnimations.posVec(0f, 1.06f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7f, KeyframeAnimations.posVec(0f, -0.33f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, -1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.posVec(0f, 2f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.7f, KeyframeAnimations.posVec(-1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-10.03f, 8.55f, -9.12f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2f, KeyframeAnimations.degreeVec(-8.96f, 5.69f, 4.12f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-9.92f, -1.3f, -7.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.degreeVec(-9.92f, 1.16f, -7.82f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(4.17f, 1.09f, -8.27f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1f, KeyframeAnimations.degreeVec(-19.98f, 0.3f, -12.74f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.degreeVec(17.62f, 2.01f, -8.04f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(-4.88f, 2.01f, -8.04f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(20.54f, 2.82f, 1.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.05f, KeyframeAnimations.degreeVec(25.21f, 2.88f, 2.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.degreeVec(-26.96f, 2.82f, 1.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(-19.15f, -0.18f, -9.24f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.65f, KeyframeAnimations.degreeVec(-5.5f, 9.48f, 15.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.9f, KeyframeAnimations.degreeVec(0.85f, 19.32f, -2.86f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(3.37f, 16.25f, -10.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(2.91f, -6.88f, 0.92f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.3f, KeyframeAnimations.degreeVec(2.62f, -4.92f, 4.81f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.degreeVec(3.78f, 8.55f, -6.93f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.posVec(0f, 1f, -2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1f, KeyframeAnimations.posVec(0f, 2f, -2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("lefthand2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(14f, -3f, 14f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.posVec(14.4f, -3f, 14f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(14f, -4.48f, 13.26f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.posVec(14.4f, -5f, 13f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.95f, KeyframeAnimations.posVec(15.4f, -5f, 13f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1f, KeyframeAnimations.posVec(14.43f, -5.35f, 12.71f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.3f, KeyframeAnimations.posVec(11.4f, -2.6f, 14.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.35f, KeyframeAnimations.posVec(11.6f, -1f, 15.05f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.4f, KeyframeAnimations.posVec(11.3f, -0.31f, 15.27f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.55f, KeyframeAnimations.posVec(13.4f, 1.85f, 16.04f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.posVec(14f, 2.12f, 16.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.7f, KeyframeAnimations.posVec(14f, 2f, 16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.95f, KeyframeAnimations.posVec(13f, 8f, 16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.05f, KeyframeAnimations.posVec(12.93f, 9.95f, 16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.posVec(13f, 11f, 16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.45f, KeyframeAnimations.posVec(13f, 10f, 16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.posVec(13.02f, 7.74f, 16.16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.6f, KeyframeAnimations.posVec(14f, 4.79f, 16.64f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.7f, KeyframeAnimations.posVec(13f, 2f, 17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.75f, KeyframeAnimations.posVec(11.89f, 0.96f, 16.21f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.85f, KeyframeAnimations.posVec(13f, -3f, 14f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.95f, KeyframeAnimations.posVec(16f, -4f, 13.37f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.05f, KeyframeAnimations.posVec(13f, -3.5f, 14.77f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.1f, KeyframeAnimations.posVec(10.89f, -1.45f, 15.45f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.15f, KeyframeAnimations.posVec(11f, 2f, 16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.posVec(13.8f, 5f, 16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.35f, KeyframeAnimations.posVec(12.5f, 3f, 17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.45f, KeyframeAnimations.posVec(11.86f, 0f, 16.12f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.55f, KeyframeAnimations.posVec(13.5f, -1f, 15f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("lefthand2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 77.5f, -90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-90f, 75f, -90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.degreeVec(-90f, 70f, -90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.1f, KeyframeAnimations.degreeVec(-82.5f, 70f, -90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.6f, KeyframeAnimations.degreeVec(75.78f, 79.53f, 68.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.75f, KeyframeAnimations.degreeVec(78.47f, 77.09f, 71.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2f, KeyframeAnimations.degreeVec(85.82f, 52.27f, 79.64f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.4f, KeyframeAnimations.degreeVec(86.23f, 47.28f, 80.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.5f, KeyframeAnimations.degreeVec(82.58f, 61.68f, 76.16f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.65f, KeyframeAnimations.degreeVec(78.47f, 77.09f, 71.7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(2.9f, KeyframeAnimations.degreeVec(-73.32f, 73.78f, -82.34f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3f, KeyframeAnimations.degreeVec(-80.1f, 74.94f, -87.49f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.25f, KeyframeAnimations.degreeVec(81.62f, 72.16f, 74.96f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(3.6f, KeyframeAnimations.degreeVec(-62.1f, 84.52f, -69.26f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.05f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition MODEL_IDLE = AnimationDefinition.Builder.withLength(2f).looping()
            .addAnimation("rightleg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("rightleg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leftleg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leftleg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("lefthand2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(16.5f, -4f, 14f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("lefthand2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-128.07f, 74.04f, -129.17f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-10.2f, 13.47f, -10.01f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("righthand",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-10f, -7f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("righthand",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-84.57f, -47.26f, 82.62f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tors",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tors",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0.5f, 2f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(29.98f, 1.25f, -2.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.8f, KeyframeAnimations.degreeVec(34.98f, 1.25f, -2.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(1.5f, KeyframeAnimations.degreeVec(29.98f, 1.25f, -2.17f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();

    public static final AnimationDefinition MODEL_ATTACK1 = AnimationDefinition.Builder.withLength(0.75f).looping()
            .addAnimation("rightleg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.35f, KeyframeAnimations.posVec(0f, 0.5f, 1.89f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("rightleg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leftleg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.posVec(0f, 0f, 3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leftleg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-2.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(10f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0.5f, 2f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.35f, KeyframeAnimations.posVec(3.5f, 2f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.posVec(-0.5f, 1f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0.5f, 2f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(29.98f, 1.25f, -2.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.35f, KeyframeAnimations.degreeVec(35.64f, 41.77f, 9.32f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(24.07f, -27.6f, -9.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(29.98f, 1.25f, -2.17f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tors",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tors",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("righthand",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-11f, -6f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(-3f, -3f, 4f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.posVec(-9f, -4f, 8f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(-11f, -6f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("righthand",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, -47.5f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-34.2f, -34.76f, 21.18f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(-71.55f, -60.87f, 69.1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-90f, -47.5f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-1f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(-1f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-10.03f, 8.55f, -9.12f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.35f, KeyframeAnimations.degreeVec(-11.2f, -27.9f, -2.3f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-10.2f, -13.61f, -5.19f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(-10.8f, 23.31f, -11.93f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-10.03f, 8.55f, -9.12f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("lefthand2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(14f, -3f, 14f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(18f, -3f, 13f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(13.44f, -5f, 12.88f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.posVec(9f, -3f, 13f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(14f, -3f, 14f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("lefthand2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 77.5f, -90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-143.6f, 68.61f, -145.53f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(-31.27f, 65.23f, -28.87f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-90f, 77.5f, -90f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.75f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
    public static final AnimationDefinition MODEL_ATTACK2 = AnimationDefinition.Builder.withLength(0.85f).looping()
            .addAnimation("rightleg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.posVec(-1f, 1f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("rightleg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leftleg",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0f, 2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.posVec(-1f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("leftleg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(22.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.degreeVec(-5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0.5f, 2f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(-1.5f, 1f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.posVec(-1.74f, 2f, 7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.posVec(-1.5f, 1f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(0.5f, 2f, 6f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("body2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(29.98f, 1.25f, -2.17f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(30.94f, -32.68f, -13.89f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.degreeVec(31.46f, 37.29f, 21.91f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(29.98f, 1.25f, -2.17f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tors",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("tors",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("righthand",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-11f, -6f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2f, KeyframeAnimations.posVec(-11.41f, -2.87f, 9.26f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(-11f, -5f, 7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.posVec(-7.16f, -2.99f, 9.08f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7f, KeyframeAnimations.posVec(-6.5f, -5f, 7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(-11f, -6f, 5f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("righthand",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, -47.5f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.2f, KeyframeAnimations.degreeVec(-99.87f, -71.09f, 101.46f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-97.31f, -59.69f, 99.71f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.degreeVec(-46.56f, -71.95f, 41.2f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7f, KeyframeAnimations.degreeVec(-50.71f, -49.7f, 44.23f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(-90f, -47.5f, 90f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone1",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone1",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(-1f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.posVec(-0.42f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(-1f, 1f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-10.03f, 8.55f, -9.12f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-11.02f, 25.76f, -12.45f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.6f, KeyframeAnimations.degreeVec(32.47f, -8.69f, -6.08f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.7f, KeyframeAnimations.degreeVec(0.52f, -15.82f, -5.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.8f, KeyframeAnimations.degreeVec(-1.98f, -15.82f, -5.39f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(-10.03f, 8.55f, -9.12f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(0f, 1f, -1f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("lefthand2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(14f, -3f, 14f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.1f, KeyframeAnimations.posVec(12f, -4.73f, 12.67f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.25f, KeyframeAnimations.posVec(5.76f, -4.29f, 9.81f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.posVec(2f, -2f, 7f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.45f, KeyframeAnimations.posVec(3.88f, -5f, 6.14f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.5f, KeyframeAnimations.posVec(9.3f, -7.73f, 6.57f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.55f, KeyframeAnimations.posVec(15.15f, -7.75f, 7.54f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.posVec(19f, -3f, 13f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(14f, -3f, 14f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("lefthand2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 77.5f, -90f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.4f, KeyframeAnimations.degreeVec(-14.73f, 31.64f, -7.85f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.65f, KeyframeAnimations.degreeVec(-149.92f, 64.42f, -152.41f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(-90f, 77.5f, -90f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.POSITION,
                            new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM)))
            .addAnimation("bone2",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM),
                            new Keyframe(0.85f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.CATMULLROM))).build();
}